
(() => {
  const KEY = "nitmexs_student_session";
  const HEARTBEAT_MS = 15000;
  const STATUS_MS = 5000;
  const BROADCAST_MS = 10000;
  const st = { studentId:"", examId:"", examName:"", attemptId:"", sequence:1, total:0, expiresAt:"", current:null, answers:{}, review:new Set(), finalized:false, timers:{}, zoom:1, warnings:0, activeInput:"", attemptStatus:"", timerFrozen:false, frozenRemainingSeconds:null, seenBroadcasts:new Set() };
  const $ = (id) => document.getElementById(id);
  const el = {
    version: $("version"), sessionStudent: $("session-student"), logoutStudent: $("logout-student"),
    openShortcuts: $("open-shortcuts"), closeShortcuts: $("close-shortcuts"), shortcutsModal: $("shortcuts-modal"),
    loadExams: $("load-exams"), examSelect: $("exam-select"), previewReference: $("preview-reference"), startAttempt: $("start-attempt"),
    status: $("student-status"), attemptMeta: $("attempt-meta"), fontSizeSelect: $("font-size-select"), highContrastToggle: $("high-contrast-toggle"),
    confirmUnansweredToggle: $("confirm-unanswered-toggle"), colorblindToggle: $("colorblind-toggle"), reducedMotionToggle: $("reduced-motion-toggle"), largeCursorToggle: $("large-cursor-toggle"),
    runDiagnostics: $("run-diagnostics"), diagnosticsResult: $("diagnostics-result"), autosaveIndicator: $("autosave-indicator"), syncHealthIndicator: $("sync-health-indicator"), heartbeatIndicator: $("heartbeat-indicator"), lowTimeAlert: $("low-time-alert"), preExamRulesBox: $("pre-exam-rules-box"),
    examName: $("exam-name"), questionProgress: $("question-progress"), questionText: $("question-text"), answerLabel: $("answer-label"), optionsList: $("options-list"), textAnswerWrap: $("text-answer-wrap"), fibInput: $("fib-input"), subjectiveInput: $("subjective-input"), wordCounter: $("word-counter"), wordWarning: $("word-warning"),
    markReview: $("mark-review"), prevQuestion: $("prev-question"), saveNext: $("save-next"), jumpUnanswered: $("jump-unanswered"), reportQuestionIssue: $("report-question-issue"), reportTechnicalIssue: $("report-technical-issue"), submitExam: $("submit-exam"),
    remainingTime: $("remaining-time"), attemptedCount: $("attempted-count"), remainingCount: $("remaining-count"), reviewCountLabel: $("review-count-label"), securityStatus: $("security-status"),
    toggleSupport: $("toggle-support"), supportPanel: $("support-panel"), toggleDiagram: $("toggle-diagram"), diagramPanel: $("diagram-panel"), toggleInputTools: $("toggle-input-tools"), inputToolsPanel: $("input-tools-panel"), broadcastFeed: $("broadcast-feed"),
    clearDiagram: $("clear-diagram"), diagramCanvas: $("diagram-canvas"), virtualKeyboard: $("virtual-keyboard"), questionZoomOut: $("question-zoom-out"), questionZoomReset: $("question-zoom-reset"), questionZoomIn: $("question-zoom-in"), questionZoomLabel: $("question-zoom-label"),
    stageLobby: $("student-stage-lobby"), stageExam: $("student-stage-exam"), stageSubmission: $("student-stage-submission"), stageLobbyPill: $("stage-pill-lobby"), stageExamPill: $("stage-pill-exam"), stageSubmissionPill: $("stage-pill-submission"),
    submissionStateText: $("submission-state-text"), finalLogout: $("final-logout"), submissionModal: $("submission-modal"), submissionModalTitle: $("submission-modal-title"), submissionModalText: $("submission-modal-text"), submissionModalOk: $("submission-modal-ok"), broadcastModal: $("broadcast-modal"), broadcastModalTitle: $("broadcast-modal-title"), broadcastModalText: $("broadcast-modal-text"), broadcastModalOk: $("broadcast-modal-ok"),
    referenceModal: $("reference-modal"), referencePreviewBox: $("reference-preview-box"), closeReference: $("close-reference")
  };
  const setStatus = (m) => { if (el.status) el.status.textContent = m; };
  const escapeHtml = (v) => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
  const label = (key, fallback) => window.NITMEXSUILabels?.get(key, fallback) ?? fallback;
  const headers = () => ({ "x-student-id": st.studentId });
  async function api(path, options = {}) { const req = { ...options, headers: { ...(options.headers || {}) } }; if (req.body && typeof req.body !== "string" && !(req.body instanceof FormData)) { req.headers["Content-Type"] = "application/json"; req.body = JSON.stringify(req.body); } const r = await fetch(path, req); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.detail || p.error || `HTTP ${r.status}`); return p.data ?? p; }
  function openDialog(d) { if (typeof d.showModal === "function") d.showModal(); else d.setAttribute("open", "open"); }
  function closeDialog(d) { if (typeof d.close === "function") d.close(); else d.removeAttribute("open"); }
  function ensureSession() { let s = null; try { s = JSON.parse(localStorage.getItem(KEY) || "null"); } catch {} if (!s?.student_id) { window.location.href = "/web?target=student&reason=login_required"; throw new Error("Student login required"); } st.studentId = s.student_id; el.sessionStudent.textContent = s.student_id; }
  function setStage(stage) {
    const order = ["lobby", "exam", "submission"];
    const currentIndex = Math.max(0, order.indexOf(stage));
    const pills = [el.stageLobbyPill, el.stageExamPill, el.stageSubmissionPill];
    st.stage = stage;
    el.stageLobby.hidden = stage !== "lobby";
    el.stageExam.hidden = stage !== "exam";
    el.stageSubmission.hidden = stage !== "submission";
    pills.forEach((pill, index) => {
      if (!pill) return;
      const isActive = index === currentIndex;
      const isCompleted = index < currentIndex;
      const isLocked = index > currentIndex;
      pill.classList.toggle("active", isActive);
      pill.classList.toggle("completed", isCompleted);
      pill.classList.toggle("locked", isLocked);
      pill.disabled = isLocked;
      if (isActive) pill.setAttribute("aria-current", "step");
      else pill.removeAttribute("aria-current");
    });
  }
  function applyA11y() { document.body.classList.toggle("student-high-contrast", el.highContrastToggle.checked); document.body.classList.toggle("student-colorblind", el.colorblindToggle.checked); document.body.classList.toggle("student-reduced-motion", el.reducedMotionToggle.checked); document.body.classList.toggle("student-large-cursor", el.largeCursorToggle.checked); document.body.dataset.fontSize = el.fontSizeSelect.value; }
  function updateZoom() { document.documentElement.style.setProperty("--student-question-zoom", String(st.zoom)); el.questionZoomLabel.textContent = `${Math.round(st.zoom * 100)}%`; }
  async function loadVersion() { try { const d = await api("/system/version"); el.version.textContent = d.version || "n/a"; } catch { el.version.textContent = "offline"; } }
  async function loadExams() { const exams = await api("/student/exams", { headers: headers() }); el.examSelect.innerHTML = `<option value="">${escapeHtml(label("student.exam_select_placeholder", "Choose an available exam..."))}</option>`; exams.forEach((exam) => { const o = document.createElement("option"); o.value = exam.id; o.textContent = `${exam.name} (${exam.status})`; el.examSelect.appendChild(o); }); setStatus(exams.length ? "Available exams loaded." : "No active exams available."); }
  async function loadRulesPreview() {
    const examId = el.examSelect.value;
    if (!examId) {
      el.preExamRulesBox.innerHTML = "<p>Select an exam to load rules.</p>";
      return;
    }
    const data = await api(`/student/exams/${examId}/rules-preview`, { headers: headers() });
    el.preExamRulesBox.innerHTML = (data.rules || [])
      .map((rule, index) => `<p>${index + 1}. ${escapeHtml(rule)}</p>`)
      .join("");
  }
  async function previewReferenceExam() { const examId = el.examSelect.value; if (!examId) { setStatus("Select an exam first."); return; } try { const d = await api(`/student/exams/${examId}/reference-preview`, { headers: headers() }); if (!d.available) { el.referencePreviewBox.innerHTML = "<p>No reference exam linked.</p>"; } else { el.referencePreviewBox.innerHTML = [`<p><strong>${escapeHtml(d.reference_exam_name)}</strong></p>`, `<p>Total preview questions: ${d.question_count}</p>`, ...d.questions.map((item) => { const q = item.question || {}; const opts = (item.options || []).map((opt) => `<li>${escapeHtml(opt.option_text)}</li>`).join(""); return `<div class="army-preview-item"><p><strong>Q${item.sequence_number}.</strong> ${escapeHtml(q.text || "")}</p>${opts ? `<ul>${opts}</ul>` : `<p class="small">Text-answer preview question.</p>`}</div>`; })].join(""); } openDialog(el.referenceModal); } catch (e) { setStatus(e.message); } }
  async function runDiagnostics() { el.diagnosticsResult.innerHTML = [`<p>Keyboard: ${document.body.dataset.keyboardSeen === "yes" ? "Detected" : "Waiting for key input"}</p>`, `<p>Mouse: ${document.body.dataset.mouseSeen === "yes" ? "Detected" : "Move mouse inside screen"}</p>`, `<p>Network: ${navigator.onLine ? "Online" : "Offline"}</p>`].join(""); }
  async function startAttempt() { const examId = el.examSelect.value; if (!examId) { setStatus("Select an exam before starting."); return; } try { const data = await api(`/student/exams/${examId}/start`, { method: "POST", headers: headers() }); st.examId = data.exam_id; st.examName = el.examSelect.options[el.examSelect.selectedIndex]?.textContent || "Exam"; st.attemptId = data.attempt_id; st.expiresAt = data.expires_at; st.sequence = 1; st.answers = {}; st.review = new Set(); st.finalized = false; st.seenBroadcasts = new Set(); await syncStatus(); hydrateQuestion(data.first_question); setStage("exam"); startPolling(); setStatus("Exam started successfully."); } catch (e) { setStatus(e.message); } }
  function hydrateQuestion(payload) { st.sequence = payload.sequence_number; st.current = payload.question || null; el.examName.textContent = st.examName || "Exam"; el.questionProgress.textContent = `Question ${st.sequence} of ${st.total || "-"}`; el.questionText.textContent = st.current?.text || "Question unavailable."; renderAnswer(payload); updateReviewLabel(); updateZoom(); }
  function buildKeyboard(type) { el.virtualKeyboard.innerHTML = ""; if (!["fib_text","short_answer","long_answer"].includes(type)) { el.virtualKeyboard.innerHTML = '<p class="small">Virtual keyboard not required for this question.</p>'; return; } ["QWERTYUIOP","ASDFGHJKL","ZXCVBNM","1234567890",".,?-/:;()"].forEach((line) => { const row = document.createElement("div"); row.className = "vk-row"; line.split("").forEach((ch) => { const b = document.createElement("button"); b.type = "button"; b.className = "vk-key"; b.textContent = ch; b.addEventListener("click", () => insertText(ch)); row.appendChild(b); }); el.virtualKeyboard.appendChild(row); }); const row = document.createElement("div"); row.className = "vk-row"; [["Space"," "],["Backspace","backspace"],["Clear","clear"]].forEach(([label,val]) => { const b = document.createElement("button"); b.type = "button"; b.className = "vk-key wide"; b.textContent = label; b.addEventListener("click", () => { if (val === "backspace") backspaceText(); else if (val === "clear") setActiveText(""); else insertText(val); }); row.appendChild(b); }); el.virtualKeyboard.appendChild(row); }
  function activeInput() { return st.activeInput === "fib" ? el.fibInput : el.subjectiveInput; }
  function insertText(v) { const i = activeInput(); if (!i || i.hidden) return; i.value += v; syncText(); }
  function backspaceText() { const i = activeInput(); if (!i || i.hidden) return; i.value = i.value.slice(0, -1); syncText(); }
  function setActiveText(v) { const i = activeInput(); if (!i || i.hidden) return; i.value = v; syncText(); }
  function syncText() { if (!st.current) return; const i = activeInput(); st.answers[st.current.id] = { text_answer: i.value }; updateWordState(); }
  function updateWordState() { if (!st.current) return; const value = (st.answers[st.current.id]?.text_answer || "").trim(); const words = value ? value.split(/\s+/).length : 0; el.wordCounter.textContent = `${label("student.word_counter_prefix", "Words")}: ${words}`; const p = st.current.word_policy || {}; if (!p.word_hard_max) { el.wordWarning.textContent = ""; return; } if (words > p.word_hard_max) { el.wordWarning.textContent = `Hard limit exceeded: ${p.word_hard_max}`; } else if (p.word_target_min && words < p.word_target_min) { el.wordWarning.textContent = `Target minimum: ${p.word_target_min}`; } else if (p.word_target_max && words > p.word_target_max) { el.wordWarning.textContent = `Target range exceeded: ${p.word_target_max}`; } else { el.wordWarning.textContent = "Within target range."; } }
  function renderAnswer(payload) { const q = payload.question || {}; const type = q.question_type || "mcq_single"; const cached = st.answers[q.id] || {}; el.optionsList.innerHTML = ""; el.textAnswerWrap.hidden = true; el.fibInput.hidden = true; el.subjectiveInput.hidden = true; el.wordWarning.textContent = ""; el.wordCounter.textContent = `${label("student.word_counter_prefix", "Words")}: 0`; buildKeyboard(type); if (type === "mcq_single" || type === "true_false") { el.answerLabel.textContent = type === "true_false" ? label("student.answer_prompt_tf", "Select True or False") : label("student.answer_prompt_mcq", "Choose One Option"); (payload.options || []).forEach((opt, index) => { const isSelected = cached.selected_option_id === opt.id; const b = document.createElement("button"); b.type = "button"; b.className = `option-btn${isSelected ? " active" : ""}`; b.setAttribute("aria-pressed", isSelected ? "true" : "false"); const optionLabel = String.fromCharCode(65 + index); b.innerHTML = `<span class="option-btn-indicator">${isSelected ? "●" : "○"}</span><span class="option-btn-text"><span class="option-btn-label">${optionLabel}.</span> ${escapeHtml(opt.option_text)}</span>${isSelected ? `<span class="option-selected-badge">${escapeHtml(label("student.option_selected", "Selected"))}</span>` : ""}`; b.addEventListener("click", () => { st.answers[q.id] = { selected_option_id: opt.id }; renderAnswer(payload); }); el.optionsList.appendChild(b); }); } else { el.answerLabel.textContent = type === "fib_text" ? label("student.answer_prompt_fib", "Type the missing word or phrase") : label("student.answer_prompt_subjective", "Write your answer"); el.textAnswerWrap.hidden = false; const text = cached.text_answer || ""; if (type === "fib_text") { st.activeInput = "fib"; el.fibInput.hidden = false; el.fibInput.value = text; } else { st.activeInput = "subjective"; el.subjectiveInput.hidden = false; el.subjectiveInput.rows = type === "long_answer" ? 10 : 5; el.subjectiveInput.value = text; } updateWordState(); } }
  async function fetchQuestion(sequence) { const d = await api(`/student/attempts/${st.attemptId}/questions/${sequence}`, { headers: headers() }); hydrateQuestion(d); }
  async function syncStatus() { if (!st.attemptId) return; const d = await api(`/student/attempts/${st.attemptId}/status`, { headers: headers() }); st.total = d.total_question_count || 0; st.expiresAt = d.expires_at || st.expiresAt; st.attemptStatus = d.status || ""; st.timerFrozen = Boolean(d.timer_frozen); st.frozenRemainingSeconds = d.frozen_remaining_seconds; el.attemptMeta.textContent = `Attempt ID: ${st.attemptId}${st.attemptStatus ? ` | Status: ${String(st.attemptStatus).toUpperCase()}` : ""}`; el.attemptedCount.textContent = String(d.answered_question_count || 0); el.remainingCount.textContent = String(Math.max(0, st.total - (d.answered_question_count || 0))); (d.answered || []).forEach((item) => { st.answers[item.question_id] = { ...(st.answers[item.question_id] || {}), selected_option_id: item.selected_option_id || null, text_answer: item.text_answer || "" }; }); if (st.attemptStatus === "paused") { el.syncHealthIndicator.textContent = st.timerFrozen ? "Exam: Paused (Timer Frozen)" : "Exam: Paused"; } updateReviewLabel(); }
  async function saveCurrentAnswer() { if (!st.current) return false; const a = st.answers[st.current.id] || {}; const hasChoice = Boolean(a.selected_option_id); const hasText = Boolean((a.text_answer || "").trim()); if (!hasChoice && !hasText) { return !el.confirmUnansweredToggle.checked || window.confirm("Current question unanswered hai. Kya aap next par jana chahte ho?"); } await api(`/student/attempts/${st.attemptId}/answers`, { method: "POST", headers: headers(), body: { question_id: st.current.id, selected_option_id: a.selected_option_id || null, text_answer: a.text_answer || null } }); el.autosaveIndicator.textContent = "Autosave: Synced"; await syncStatus(); return true; }
  async function saveAndMove(nextSequence) { try { el.autosaveIndicator.textContent = "Autosave: Saving..."; const ok = await saveCurrentAnswer(); if (!ok) { el.autosaveIndicator.textContent = "Autosave: Cancelled"; return; } if (nextSequence >= 1 && nextSequence <= st.total) await fetchQuestion(nextSequence); setStatus("Answer saved."); } catch (e) { el.autosaveIndicator.textContent = "Autosave: Error"; setStatus(e.message); } }
  function markCurrentQuestion() { if (!st.current) return; if (st.review.has(st.current.id)) st.review.delete(st.current.id); else st.review.add(st.current.id); updateReviewLabel(); }
  function updateReviewLabel() { el.reviewCountLabel.textContent = `${label("student.marked_review_prefix", "Marked for review")}: ${st.review.size}`; if (st.current) el.markReview.textContent = st.review.has(st.current.id) ? label("student.unmark_review", "Unmark Current Question") : label("student.mark_review", "Mark Current Question"); }
  async function jumpFirstUnanswered() { for (let i = 1; i <= st.total; i += 1) { const q = await api(`/student/attempts/${st.attemptId}/questions/${i}`, { headers: headers() }); const id = q.question?.id; const a = id ? st.answers[id] : null; if (!a || (!a.selected_option_id && !(a.text_answer || "").trim())) { hydrateQuestion(q); return; } } setStatus("All questions already have answers."); }
  function formatSeconds(totalSeconds) { const total = Math.max(0, Number(totalSeconds || 0)); const h = String(Math.floor(total / 3600)).padStart(2, "0"); const m = String(Math.floor((total % 3600) / 60)).padStart(2, "0"); const s = String(total % 60).padStart(2, "0"); return `${h}:${m}:${s}`; }
  function formatRemaining() { if (st.attemptStatus === "paused" && st.timerFrozen && st.frozenRemainingSeconds != null) return formatSeconds(st.frozenRemainingSeconds); if (!st.expiresAt) return "--:--"; const ms = Math.max(0, new Date(st.expiresAt).getTime() - Date.now()); return formatSeconds(Math.floor(ms / 1000)); }
  async function tickClock() { el.remainingTime.textContent = formatRemaining(); if (!st.expiresAt || st.finalized || (st.attemptStatus === "paused" && st.timerFrozen)) return; const left = new Date(st.expiresAt).getTime() - Date.now(); if (left <= 0 && st.attemptStatus !== "paused") { await finalize(true); return; } if (left <= 300000) { el.lowTimeAlert.hidden = false; el.lowTimeAlert.textContent = "Low time alert: final 5 minutes running."; } }
  async function pollBroadcasts() { if (!st.attemptId) return; const d = await api(`/student/attempts/${st.attemptId}/broadcasts`, { headers: headers() }); const items = d.broadcasts || []; if (!items.length) return; el.broadcastFeed.innerHTML = items.map((item) => `<p><strong>${escapeHtml(item.severity || "info")}</strong>: ${escapeHtml(item.message || "")}</p>`).join(""); const unseen = items.filter((item) => !st.seenBroadcasts.has(item.id)); unseen.forEach((item) => st.seenBroadcasts.add(item.id)); const popupItem = unseen.find((item) => ["warn", "critical"].includes(String(item.severity || "").toLowerCase())) || unseen[0]; if (popupItem) { el.broadcastModalTitle.textContent = `Broadcast: ${String(popupItem.severity || "info").toUpperCase()}`; el.broadcastModalText.textContent = popupItem.message || ""; openDialog(el.broadcastModal); } await api(`/student/attempts/${st.attemptId}/broadcasts/ack`, { method: "POST", headers: headers(), body: { broadcast_ids: items.map((item) => item.id) } }).catch(() => ({})); }
  async function checkHeartbeat() { const start = performance.now(); try { await api("/system/version"); const ms = Math.round(performance.now() - start); el.heartbeatIndicator.textContent = `Server: Healthy (${ms}ms)`; el.syncHealthIndicator.textContent = "LAN: Healthy"; } catch { el.heartbeatIndicator.textContent = "Server: Unreachable"; el.syncHealthIndicator.textContent = "LAN: Degraded"; } }
  async function pollStatus() { try { await syncStatus(); await pollBroadcasts(); await tickClock(); } catch (e) { el.syncHealthIndicator.textContent = "LAN: Retry pending"; setStatus(e.message); } }
  function startPolling() { stopPolling(); st.timers.status = window.setInterval(pollStatus, STATUS_MS); st.timers.heartbeat = window.setInterval(checkHeartbeat, HEARTBEAT_MS); st.timers.broadcast = window.setInterval(pollBroadcasts, BROADCAST_MS); pollStatus(); checkHeartbeat(); }
  function stopPolling() { Object.values(st.timers).forEach((id) => id && window.clearInterval(id)); st.timers = {}; }
  async function report(kind) { if (!st.attemptId || !st.current) return; const note = window.prompt(`Describe the ${kind} briefly:`) || ""; const path = kind === "technical issue" ? "technical-issue" : "question-issue"; const body = kind === "technical issue" ? { issue_type: "technical_issue", note } : { question_id: st.current.id, issue_type: "content_issue", note }; try { await api(`/student/attempts/${st.attemptId}/${path}`, { method: "POST", headers: headers(), body }); setStatus(`${kind} reported.`); } catch (e) { setStatus(e.message); } }
  async function finalize(autoSubmitted) { if (!st.attemptId || st.finalized) return; try { const path = autoSubmitted ? "auto-submit" : "finalize"; const d = await api(`/student/attempts/${st.attemptId}/${path}`, { method: "POST", headers: headers() }); st.finalized = true; stopPolling(); setStage("submission"); el.submissionStateText.textContent = autoSubmitted ? "Time expired. Awaiting acknowledgement." : "Manual submission completed. Awaiting acknowledgement."; el.submissionModalTitle.textContent = autoSubmitted ? "Time Over" : "Exam Submitted"; el.submissionModalText.textContent = autoSubmitted ? "You are out of time. Better luck next time. Your exam has been submitted." : (d.grading === "pending_review" ? "Congratulations, your exam has been submitted. Review-based marking is pending." : "You have completed your exam within the time limit."); openDialog(el.submissionModal); } catch (e) { setStatus(e.message); } }
  function logout() { localStorage.removeItem(KEY); window.location.href = "/web"; }
  function bindCanvas() { const canvas = el.diagramCanvas; if (!canvas) return; const ctx = canvas.getContext("2d"); ctx.lineWidth = 2; ctx.strokeStyle = "#7bc3ff"; const p = (e) => { const r = canvas.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top }; }; canvas.addEventListener("pointerdown", (e) => { st.drawing = true; const pt = p(e); ctx.beginPath(); ctx.moveTo(pt.x, pt.y); }); canvas.addEventListener("pointermove", (e) => { if (!st.drawing) return; const pt = p(e); ctx.lineTo(pt.x, pt.y); ctx.stroke(); }); ["pointerup", "pointerleave"].forEach((name) => canvas.addEventListener(name, () => { st.drawing = false; })); el.clearDiagram.addEventListener("click", () => ctx.clearRect(0, 0, canvas.width, canvas.height)); }
  function updateSecurity() { el.securityStatus.textContent = `Security status: warnings ${st.warnings}`; if (st.warnings >= 3) el.securityStatus.textContent += " (reported)"; }
  function bindSecurity() { window.addEventListener("beforeunload", (e) => { if (!st.finalized && !el.stageExam.hidden) { e.preventDefault(); e.returnValue = "Exam in progress."; } }); document.addEventListener("contextmenu", (e) => e.preventDefault()); ["copy","cut","paste"].forEach((name) => document.addEventListener(name, (e) => { if (!el.stageExam.hidden) { e.preventDefault(); st.warnings += 1; updateSecurity(); } })); document.addEventListener("visibilitychange", () => { if (!el.stageExam.hidden && document.hidden) { st.warnings += 1; updateSecurity(); } }); }
  function bindShortcuts() { document.addEventListener("keydown", (e) => { document.body.dataset.keyboardSeen = "yes"; if (el.stageExam.hidden) return; const key = e.key.toLowerCase(); if (["s","m","a","q","?"].includes(key)) e.preventDefault(); if (key === "s") saveAndMove(Math.min(st.total, st.sequence + 1)); else if (key === "m") markCurrentQuestion(); else if (key === "a") jumpFirstUnanswered(); else if (key === "q" || key === "?") openDialog(el.shortcutsModal); }); document.addEventListener("mousemove", () => { document.body.dataset.mouseSeen = "yes"; }); }
  function bindEvents() {
    el.logoutStudent.addEventListener("click", logout); el.finalLogout.addEventListener("click", logout); el.loadExams.addEventListener("click", () => loadExams().catch((e) => setStatus(e.message)));
    el.examSelect.addEventListener("change", () => loadRulesPreview().catch((e) => setStatus(e.message)));
    el.previewReference.addEventListener("click", previewReferenceExam); el.closeReference.addEventListener("click", () => closeDialog(el.referenceModal)); el.startAttempt.addEventListener("click", startAttempt); el.runDiagnostics.addEventListener("click", runDiagnostics);
    el.openShortcuts.addEventListener("click", () => openDialog(el.shortcutsModal)); el.closeShortcuts.addEventListener("click", () => closeDialog(el.shortcutsModal)); el.submissionModalOk.addEventListener("click", () => { closeDialog(el.submissionModal); el.finalLogout.hidden = false; }); el.broadcastModalOk.addEventListener("click", () => closeDialog(el.broadcastModal));
    el.markReview.addEventListener("click", markCurrentQuestion); el.prevQuestion.addEventListener("click", () => fetchQuestion(Math.max(1, st.sequence - 1)).catch((e) => setStatus(e.message))); el.saveNext.addEventListener("click", () => saveAndMove(Math.min(st.total, st.sequence + 1)));
    el.jumpUnanswered.addEventListener("click", () => jumpFirstUnanswered().catch((e) => setStatus(e.message))); el.reportQuestionIssue.addEventListener("click", () => report("question issue")); el.reportTechnicalIssue.addEventListener("click", () => report("technical issue")); el.submitExam.addEventListener("click", () => { const remaining = Number(el.remainingCount.textContent || "0"); if (el.confirmUnansweredToggle.checked && remaining > 0 && !window.confirm(`Abhi ${remaining} unanswered question(s) baki hain. Kya aap exam submit karna chahte ho?`)) return; finalize(false); });
    el.toggleSupport.addEventListener("click", () => { el.supportPanel.hidden = !el.supportPanel.hidden; }); el.toggleDiagram.addEventListener("click", () => { el.diagramPanel.hidden = !el.diagramPanel.hidden; }); el.toggleInputTools.addEventListener("click", () => { el.inputToolsPanel.hidden = !el.inputToolsPanel.hidden; });
    el.fibInput.addEventListener("input", syncText); el.subjectiveInput.addEventListener("input", syncText);
    el.questionZoomOut.addEventListener("click", () => { st.zoom = Math.max(0.8, st.zoom - 0.1); updateZoom(); }); el.questionZoomReset.addEventListener("click", () => { st.zoom = 1; updateZoom(); }); el.questionZoomIn.addEventListener("click", () => { st.zoom = Math.min(1.8, st.zoom + 0.1); updateZoom(); });
    [el.highContrastToggle, el.confirmUnansweredToggle, el.colorblindToggle, el.reducedMotionToggle, el.largeCursorToggle, el.fontSizeSelect].forEach((c) => c.addEventListener("change", applyA11y));
  }
  try { ensureSession(); setStage("lobby"); bindEvents(); bindCanvas(); bindSecurity(); bindShortcuts(); applyA11y(); updateZoom(); loadVersion(); loadExams().then(() => loadRulesPreview().catch(() => {})).catch((e) => setStatus(e.message)); } catch {}
})();
